shellEmulator: true

trustPolicy: no-downgrade

catalogs:
  build:
    tsdown: ^0.20.3
  hook:
    lint-staged: ^16.2.7
    simple-git-hooks: ^2.13.1
  lint:
    eslint-formatter-mo: ^2.4.1
  peer:
    "@eslint-react/eslint-plugin": ^2.13.0
    "@unocss/eslint-plugin": ^66.6.2
    eslint: ^10.0.2
    eslint-plugin-astro: ^1.6.0
    eslint-plugin-format: ^2.0.1
    eslint-plugin-react-hooks: ^7.0.1
    eslint-plugin-react-refresh: ^0.5.2
    eslint-plugin-solid: ^0.14.5
    eslint-plugin-svelte: ^3.15.0
    svelte: ^5.53.5
    svelte-eslint-parser: ^1.5.1
    vue: ^3.5.29
  prod:
    "@antfu/eslint-config": ~7.6.1
    cac: ^6.7.14
    defu: ^6.1.4
    eslint-flat-config-utils: ^3.0.1
    local-pkg: ^1.1.2
  script:
    "@antfu/ni": ^28.2.0
    bumpp: ^10.4.1
    tsx: ^4.21.0
  test:
    execa: ^9.6.1
    tinyglobby: ^0.2.15
    vite: ^7.3.1
    vitest: ^4.0.18
  types:
    "@types/node": ^24.10.15
    typescript: ^5.9.3
