catalogs:
  build:
    tsdown: ^0.16.6
    tsup: ^8.5.1
  hook:
    lint-staged: ^16.2.6
    simple-git-hooks: ^2.13.1
  lint:
    eslint-formatter-mo: ^2.4.1
  peer:
    "@eslint-react/eslint-plugin": ^2.3.7
    "@unocss/eslint-plugin": ^66.5.7
    eslint: ^9.39.1
    eslint-plugin-astro: ^1.5.0
    eslint-plugin-format: ^1.0.2
    eslint-plugin-react-hooks: ^7.0.1
    eslint-plugin-react-refresh: ^0.4.24
    eslint-plugin-solid: ^0.14.5
    eslint-plugin-svelte: ^3.13.0
    svelte: ^5.43.14
    svelte-eslint-parser: ^1.4.0
    vue: ^3.5.24
  prod:
    "@antfu/eslint-config": ^6.2.0
    cac: ^6.7.14
    defu: ^6.1.4
    eslint-flat-config-utils: ^2.1.4
    local-pkg: ^1.1.2
  script:
    "@antfu/ni": ^27.0.1
    bumpp: ^10.3.1
    tsx: ^4.20.6
  test:
    execa: ^9.6.0
    tinyglobby: ^0.2.15
    vite: ^7.2.2
    vitest: ^4.0.10
  types:
    "@types/node": ^24.10.1
    typescript: ^5.9.3
